name: Conditional Workflow

on:
    push:
        paths:
            - 'src/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              
            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
      
            - name: Ejecutar tests con pytest
              run: pytest --cov=src --cov-report=term-missing            