name: CI con notificación

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest

      - name: Notificación por Discord o Slack
        if: always()
        run: |
          STATUS="✅ Éxito"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ Fallo"
          fi
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"📣 Workflow completado con estado: $STATUS\"}" \
            ${{ secrets.WEBHOOK_URL }}
