name: Workflow Reutilizable

on:
  workflow_call: 

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ejecutar tests con cobertura
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest --cov=src --cov-report=term-missing
  
      - name: Ejecutar tests con pytest
        run: pytest --cov=src --cov-report=term-missing
